### ISSUE TITLE
Vet'ion KC sometimes gets pulled as Vorkath

### ISSUE THREAD

**Issue by Lehrules** [maxswa/osrs-json-hiscores#16] opened 2020-07-30 16:15 UTC
Sometimes vorkath kc pulls its data from vet'ion's HS data. I don't know how to reproduce it. Happens maybe 1/8th of the time. Could also just be my code.

**Comment by maxswa** [comment] 2020-07-30 21:06
I'll look into reproducing this, could you post a link to / snippet of your code to help diagnose the issue?

**Comment by Lehrules** [comment] 2020-07-31 02:38
Sure. 

`function updateHiscores(channel){
        hiscores.getStats(channelRSN[channel]).then(hiscoresRes => {
            if(!hiscoresRes){ console.log(`${main.tStamp()}: ${chatter.channel}: update.js did not return any hiscores.`); return;}
                 updatedCounts = [];
                 var killcounts = hiscoresRes.main.bosses
                 var clueKeys = Object.keys(hiscoresRes.main.clues);
                clueKeys.forEach((element, index, currArray)=>{
                   killcounts[`clues_${clueKeys[index]}`] = hiscoresRes.main.clues[element]
                });
            //console.log(JSON.stringify(killcounts, null, 1));

            var dbo = myDb.db(channel).collection("guessConfig");
            dbo.find({"hiscoreName": {$exists: true}}).toArray( function(err, findResult) {
                    if (err) throw err;
                    if(findResult){
                        findResult.forEach((element, currIndex, currArray) => {
                            if(killcounts[element.hiscoreName]){
                                var name = element.hiscoreName;
                                var oldKC = element.kc;
                                var newKC = killcounts[element.hiscoreName].score;
                                var oldRank = element.rank;
                                var newRank = killcounts[element.hiscoreName].rank;
                                var diffRank = oldRank - newRank;
                                if(!Number(newKC) || Number(newKC) == -1){ console.log(`###No Data for ${channel}:${name}###`); return};
                                if(newKC !== oldKC || oldRank !== newRank){
                                    dbo.updateOne({"_id": element["_id"]}, {$set: {"kc": killcounts[element.hiscoreName].score, "rank": killcounts[element.hiscoreName].rank}}, function(err,updateRes){
                                        if (err) throw err;
                                        if(updateRes){
                                          if(newKC !== oldKC){
                                              console.log(`${element.name}: ${oldKC} -> ${newKC} || ${JSON.stringify(killcounts[element.hiscoreName])}`);
                                              updatedCounts.push(`${element.name}: ${oldKC}->${newKC} (Rank:${newRank})`)
                                              insertNewGuess({
                                                 name: `${element.name}: ${oldKC}->${newKC} (Rank:${newRank})`,
                                                 status: "hs"
                                              });
                                          };
                                          console.log(`${currIndex}/${currArray.length} : ${updatedCounts.length}`);
                                          if(currIndex == currArray.length - 1){
                                                console.log(`${main.tStamp()}:${chatter.channel}: [${msg}]`);
                                            };
                                        };
                                    });
                                };

                            };
                        });
                    }else if(!findResult){
                        Bot.say(`@${chatter.display_name}, something went wrong.`, chatter.channel);
                    };
            });

        }).catch(err => {
            console.log(err)
            Bot.say(`MrDestructoid @${chatter.display_name}, guessUpdate failed.`, chatter.channel);
        });
    }; //end function`

**Comment by Lehrules** [comment] 2020-07-31 18:39
I'm going to write a save of the raw hiscores info it pulls so I can see if it's the package or my code

**Comment by Lehrules** [comment] 2020-07-31 19:20
https://i.imgur.com/Q0LrSer.png

it's pulling vetion data as vorkath.
RSN Hey_Jase

**Comment by Lehrules** [comment] 2020-08-04 22:02
For a simple fix I just check if KC is lower than the last KC I saved last and don't save if it's lower.

**Comment by maxswa** [comment] 2020-08-04 22:08
Sorry for the delay, thanks for the info. I'll look into a fix for this. Also as a workaround for now I would also suggest using `getStatsByGamemode` vs `getStats` since you're only using stats from `main` and Jagex's hiscores are still very unstable at the moment.

**Comment by KiwiZ0** [comment] 2021-03-25 00:37
Also getting this

**Comment by maxswa** [comment] 2021-03-25 01:22
> Also getting this

@KiwiZ0 can you share your version of `osrs-json-hiscores` and your implementation?

**Comment by KiwiZ0** [comment] 2021-03-25 02:01
Idk how to share my version but I just downloaded it today and was playing with how I might use it while I think of my design for a 'reaper task' system I want to make on my bot
![image](https://user-images.githubusercontent.com/9370847/112407430-751df480-8cec-11eb-9d6f-87de06f46b83.png)

**Comment by KiwiZ0** [comment] 2021-03-25 02:25
Looks like starting somewhere towards the bottom of the 'bosses' everything is shifted down, Zulrah is gone

**Comment by maxswa** [comment] 2021-03-25 02:39
Oh I see, looks like your issue is due to the Tempoross update. I'll push an update to support the new boss.

**Comment by maxswa** [comment] 2021-03-25 02:52
`osrs-json-hiscores@2.4.0` has now been published which adds support for Tempoross. Please upgrade to this latest version and let me know if that fixes your issue.

**Comment by KiwiZ0** [comment] 2021-03-25 13:02
Fixed, thank you very much!

**Comment by maxswa** [comment] 2021-06-04 02:48
Cannot find a way to reproduce this, closing for now.

**Closed by maxswa** 2021-06-04 02:48 UTC
Labels: question
